In [1]:
import torch

In [3]:
data=[[1, 2, 3], [4, 5, 6]]
xdata=torch.tensor(data)
print(xdata)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [4]:
import numpy as np
np_array = np.array(data)
x_np=torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [5]:
x_ones=torch.ones_like(xdata)
print(x_ones)
x_rand=torch.rand_like(xdata, dtype=torch.float)
print(x_rand)

tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0.6766, 0.0329, 0.0160],
        [0.2541, 0.1685, 0.3657]])


In [7]:
shape=(3, 6)
ones_tensor=torch.ones(shape)
zeros_tensor=torch.zeros(shape)
torch.manual_seed(5342)
rand_tensor=torch.rand(shape)
empty_tensor=torch.empty(shape)
print(ones_tensor)
print(zeros_tensor)
print(rand_tensor)
print(empty_tensor)


tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0.9134, 0.4344, 0.1817, 0.4808, 0.4696, 0.2421],
        [0.4272, 0.5655, 0.7288, 0.1206, 0.5242, 0.2147],
        [0.9779, 0.7167, 0.2870, 0.4134, 0.1970, 0.8015]])
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])


In [8]:
x=torch.empty(3,6,2)
print(x)
print(x.shape)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]])
torch.Size([3, 6, 2])


In [9]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a.dtype)
a = torch.ones((2, 3), dtype=torch.float64)
print(a.dtype)
a = torch.ones((2, 3), dtype=torch.int8)
print(a.dtype)
a = torch.ones((2, 3), dtype=torch.int32)
print(a.dtype)
a = torch.ones((2, 3), dtype=torch.int64)
print(a.dtype)
a = torch.ones((2, 3), dtype=torch.bool)
print(a.dtype)


torch.int16
torch.float64
torch.int8
torch.int32
torch.int64
torch.bool


In [10]:
# Create a tensor
tensor = torch.rand(3, 2)
print(f"Device tensor is initially stored on: {tensor.device}")




Device tensor is initially stored on: cpu


In [11]:
# Check if GPU is available and move tensor to GPU if it is
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
    print(f"Device tensor is now stored on: {tensor.device}")
else:
    print("CUDA is not available. Tensor remains on CPU.")
    

CUDA is not available. Tensor remains on CPU.


In [12]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}","\n")
print(f"First column: {tensor[:, 0]}","\n")
print(f"Last column: {tensor[:, -1]}","\n")
tensor[:,1] = 0 # set all elements in second column to 0
print(tensor)


First row: tensor([1., 1., 1., 1.]) 

First column: tensor([1., 1., 1., 1.]) 

Last column: tensor([1., 1., 1., 1.]) 

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [13]:
ones = torch.zeros(2, 2) + 1 # adding 1 to a tensor of zeros
twos = torch.ones(2, 2) * 2 # multiplying a tensor of ones by 2
threes = (torch.ones(2, 2) * 7 - 1) / 2 # chaining operations
fours = twos ** 2 # squaring a tensor
sqrt2s = twos ** 0.5 # square root of a tensor

print(ones,"\n")
print(twos,"\n")
print(threes,"\n")
print(fours,"\n")
print(sqrt2s,"\n")





tensor([[1., 1.],
        [1., 1.]]) 

tensor([[2., 2.],
        [2., 2.]]) 

tensor([[3., 3.],
        [3., 3.]]) 

tensor([[4., 4.],
        [4., 4.]]) 

tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]]) 



In [15]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]]) # element-wise exponentiation
print(powers2,"\n")
fives = ones + powers2 # element-wise addition
print(fives,"\n")
dozens = threes * powers2 # element-wise multiplication
print(dozens,"\n")

tensor([[ 2.,  4.],
        [ 8., 16.]]) 

tensor([[ 3.,  5.],
        [ 9., 17.]]) 

tensor([[ 6., 12.],
        [24., 48.]]) 



In [16]:
rand = torch.rand(2, 4) # random tensor
doubled = rand * (torch.ones(1, 4) * 2) # broadcasting
print(rand)
print(doubled)


tensor([[0.2099, 0.2497, 0.7165, 0.6052],
        [0.2578, 0.5984, 0.1647, 0.0950]])
tensor([[0.4198, 0.4994, 1.4331, 1.2103],
        [0.5156, 1.1969, 0.3294, 0.1901]])


In [17]:
a = torch.ones(4, 3, 2)
b = a * torch.rand(3, 2)
print(b, "\n") # 3rd & 2nd dims identical to a, dim 1 absent
c = a * torch.rand(4, 1, 2)
print(c, "\n") # 3rd dim = 1, 2nd dim identical to a
d = a * torch.rand(1, 3, 2)
print(d, "\n") # 3rd dim identical to a, 2nd dim = 1


tensor([[[0.7679, 0.2979],
         [0.2714, 0.8352],
         [0.1377, 0.0667]],

        [[0.7679, 0.2979],
         [0.2714, 0.8352],
         [0.1377, 0.0667]],

        [[0.7679, 0.2979],
         [0.2714, 0.8352],
         [0.1377, 0.0667]],

        [[0.7679, 0.2979],
         [0.2714, 0.8352],
         [0.1377, 0.0667]]]) 

tensor([[[0.8824, 0.6409],
         [0.8824, 0.6409],
         [0.8824, 0.6409]],

        [[0.7558, 0.4031],
         [0.7558, 0.4031],
         [0.7558, 0.4031]],

        [[0.8364, 0.1827],
         [0.8364, 0.1827],
         [0.8364, 0.1827]],

        [[0.7059, 0.9241],
         [0.7059, 0.9241],
         [0.7059, 0.9241]]]) 

tensor([[[0.7354, 0.7719],
         [0.4473, 0.1884],
         [0.7068, 0.8141]],

        [[0.7354, 0.7719],
         [0.4473, 0.1884],
         [0.7068, 0.8141]],

        [[0.7354, 0.7719],
         [0.4473, 0.1884],
         [0.7068, 0.8141]],

        [[0.7354, 0.7719],
         [0.4473, 0.1884],
         [0.7068, 0.8141]]]) 

In [19]:
import math

a = torch.rand(2, 4) * 2 - 1 # random tensor in range [-1, 1]
print(a,"\n")
print(torch.abs(a),"\n") #absolute value
print(torch.ceil(a),"\n") #ceiling
print(torch.floor(a),"\n") #floor
print(torch.clamp(a, -0.5, 0.5)) #clamping: values < -0.5 set to -0.5, values > 0.5 set to 0.5


tensor([[ 0.4161, -0.8475, -0.1534,  0.4387],
        [ 0.5731,  0.5222, -0.9818,  0.4168]]) 

tensor([[0.4161, 0.8475, 0.1534, 0.4387],
        [0.5731, 0.5222, 0.9818, 0.4168]]) 

tensor([[1., -0., -0., 1.],
        [1., 1., -0., 1.]]) 

tensor([[ 0., -1., -1.,  0.],
        [ 0.,  0., -1.,  0.]]) 

tensor([[ 0.4161, -0.5000, -0.1534,  0.4387],
        [ 0.5000,  0.5000, -0.5000,  0.4168]])


In [20]:
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4]) # angles in radians
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles,"\n")
print(sines,"\n")
print(inverses,"\n")



Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562]) 

tensor([0.0000, 0.7071, 1.0000, 0.7071]) 

tensor([0.0000, 0.7854, 1.5708, 0.7854]) 



In [21]:
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))


tensor([3, 2, 1])


In [22]:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
print(d,"\n")
e = torch.ones(1, 2)  # many comparison ops support broadcasting!
print(e,"\n")
print(torch.eq(d, e))  # returns a tensor of type bool



Broadcasted, element-wise equality comparison:
tensor([[1., 2.],
        [3., 4.]]) 

tensor([[1., 1.]]) 

tensor([[ True, False],
        [False, False]])


In [23]:
d = torch.tensor([[1., 2.], [3., 4.]])
print(torch.max(d))
print(torch.max(d).item())
print(torch.mean(d))
print(torch.std(d))
print(torch.prod(d))
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2])))  # filter unique elements


tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])
