In [2]:
import torch

In [3]:
data=[[1, 2, 3], [4, 5, 6]]
xdata=torch.tensor(data)
print(xdata)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [4]:
import numpy as np
np_array = np.array(data)
x_np=torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [5]:
x_ones=torch.ones_like(xdata)
print(x_ones)
x_rand=torch.rand_like(xdata, dtype=torch.float)
print(x_rand)

tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0.8387, 0.8657, 0.1878],
        [0.5997, 0.9827, 0.0413]])


In [6]:
shape=(3, 6)
ones_tensor=torch.ones(shape)
zeros_tensor=torch.zeros(shape)
torch.manual_seed(5342)
rand_tensor=torch.rand(shape)
empty_tensor=torch.empty(shape)
print(ones_tensor)
print(zeros_tensor)
print(rand_tensor)
print(empty_tensor)


tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0.9134, 0.4344, 0.1817, 0.4808, 0.4696, 0.2421],
        [0.4272, 0.5655, 0.7288, 0.1206, 0.5242, 0.2147],
        [0.9779, 0.7167, 0.2870, 0.4134, 0.1970, 0.8015]])
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])


In [7]:
x=torch.empty(3,6,2)
print(x)
print(x.shape)

tensor([[[8.3946e-28, 8.1696e-43],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]]])
torch.Size([3, 6, 2])


In [8]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a.dtype)
a = torch.ones((2, 3), dtype=torch.float64)
print(a.dtype)
a = torch.ones((2, 3), dtype=torch.int8)
print(a.dtype)
a = torch.ones((2, 3), dtype=torch.int32)
print(a.dtype)
a = torch.ones((2, 3), dtype=torch.int64)
print(a.dtype)
a = torch.ones((2, 3), dtype=torch.bool)
print(a.dtype)


torch.int16
torch.float64
torch.int8
torch.int32
torch.int64
torch.bool


In [9]:
# Create a tensor
tensor = torch.rand(3, 2)
print(f"Device tensor is initially stored on: {tensor.device}")




Device tensor is initially stored on: cpu


In [ ]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
    print(f"Device tensor is now stored on: {tensor.device}")
else:
    print("CUDA is not available. Tensor remains on CPU.")
    

CUDA is not available. Tensor remains on CPU.


In [ ]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}","\n")
print(f"First column: {tensor[:, 0]}","\n")
print(f"Last column: {tensor[:, -1]}","\n")
tensor[:,1] = 0 
print(tensor)


First row: tensor([1., 1., 1., 1.]) 

First column: tensor([1., 1., 1., 1.]) 

Last column: tensor([1., 1., 1., 1.]) 

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
ones = torch.zeros(2, 2) + 1 
twos = torch.ones(2, 2) * 2 
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2 
sqrt2s = twos ** 0.5 

print(ones,"\n")
print(twos,"\n")
print(threes,"\n")
print(fours,"\n")
print(sqrt2s,"\n")

tensor([[1., 1.],
        [1., 1.]]) 

tensor([[2., 2.],
        [2., 2.]]) 

tensor([[3., 3.],
        [3., 3.]]) 

tensor([[4., 4.],
        [4., 4.]]) 

tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]]) 



In [ ]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]]) 
print(powers2,"\n")
fives = ones + powers2 
print(fives,"\n")
dozens = threes * powers2 
print(dozens,"\n")

tensor([[ 2.,  4.],
        [ 8., 16.]]) 

tensor([[ 3.,  5.],
        [ 9., 17.]]) 

tensor([[ 6., 12.],
        [24., 48.]]) 



In [ ]:
rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)
print(rand)
print(doubled)

tensor([[0.2099, 0.2497, 0.7165, 0.6052],
        [0.2578, 0.5984, 0.1647, 0.0950]])
tensor([[0.4198, 0.4994, 1.4331, 1.2103],
        [0.5156, 1.1969, 0.3294, 0.1901]])


In [ ]:
a = torch.ones(4, 3, 2)
print(a)
b = a * torch.rand(3, 2)
print(b, "\n") 
c = a * torch.rand(4, 1, 2)
print(c, "\n") 
d = a * torch.rand(1, 3, 2)
print(d, "\n") 


tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])
tensor([[[0.6106, 0.5466],
         [0.5743, 0.3525],
         [0.5677, 0.6100]],

        [[0.6106, 0.5466],
         [0.5743, 0.3525],
         [0.5677, 0.6100]],

        [[0.6106, 0.5466],
         [0.5743, 0.3525],
         [0.5677, 0.6100]],

        [[0.6106, 0.5466],
         [0.5743, 0.3525],
         [0.5677, 0.6100]]]) 

tensor([[[0.5719, 0.0967],
         [0.5719, 0.0967],
         [0.5719, 0.0967]],

        [[0.3208, 0.5908],
         [0.3208, 0.5908],
         [0.3208, 0.5908]],

        [[0.9659, 0.0275],
         [0.9659, 0.0275],
         [0.9659, 0.0275]],

        [[0.3514, 0.1094],
         [0.3514, 0.1094],
         [0.3514, 0.1094]]]) 

tensor([[[0.5027, 0.8610],
         [0.3222, 0.4128],
         [0.5178, 0.7931]],

        [[0.5

In [ ]:
import math
a = torch.rand(2, 4) * 2 - 1
print(a,"\n")
print(torch.abs(a),"\n") 
print(torch.ceil(a),"\n") 
print(torch.floor(a),"\n") 
print(torch.clamp(a, -0.5, 0.5)) 

tensor([[ 0.5830, -0.1773,  0.1101,  0.6310],
        [ 0.2895, -0.3440, -0.1988, -0.3762]]) 

tensor([[0.5830, 0.1773, 0.1101, 0.6310],
        [0.2895, 0.3440, 0.1988, 0.3762]]) 

tensor([[1., -0., 1., 1.],
        [1., -0., -0., -0.]]) 

tensor([[ 0., -1.,  0.,  0.],
        [ 0., -1., -1., -1.]]) 

tensor([[ 0.5000, -0.1773,  0.1101,  0.5000],
        [ 0.2895, -0.3440, -0.1988, -0.3762]])


In [ ]:
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4]) 
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles,"\n")
print(sines,"\n")
print(inverses,"\n")



Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562]) 

tensor([0.0000, 0.7071, 1.0000, 0.7071]) 

tensor([0.0000, 0.7854, 1.5708, 0.7854]) 



In [18]:
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))


tensor([3, 2, 1])


In [ ]:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
print(d,"\n")
e = torch.ones(1, 2)  
print(e,"\n")
print(torch.eq(d, e)) 


Broadcasted, element-wise equality comparison:
tensor([[1., 2.],
        [3., 4.]]) 

tensor([[1., 1.]]) 

tensor([[ True, False],
        [False, False]])


In [ ]:
d = torch.tensor([[1., 2.], [3., 4.]])
print(torch.max(d))
print(torch.max(d).item())
print(torch.mean(d))
print(torch.std(d))
print(torch.prod(d))
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2])))

tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])


In [24]:
v1=torch.tensor([1,0,0])
v2=torch.tensor([0,1,0])
print(torch.cross(v1,v2),'/n')
m1=torch.rand(2,2)
m2=torch.tensor([[3.0,0.0],[0.0,3.0]])
print(m1)
m3=torch.matmul(m1,m2)
print(m3)
print(torch.svd(m3))

tensor([0, 0, 1]) /n
tensor([[0.6542, 0.3798],
        [0.8130, 0.5414]])
tensor([[1.9627, 1.1395],
        [2.4389, 1.6243]])
torch.return_types.svd(
U=tensor([[-0.6121, -0.7907],
        [-0.7907,  0.6121]]),
S=tensor([3.7047, 0.1103]),
V=tensor([[-0.8449, -0.5350],
        [-0.5350,  0.8449]]))


In [27]:
a=torch.tensor([0,math.pi/4,math.pi/2,3*math.pi/4])
print(a)
print(torch.sin(a))
print(a,'\n')
b=torch.tensor([0,math.pi/4,math.pi/2,3*math.pi/4])
print(b)
print(torch.sin_(b))
print(b)

tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562]) 

tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [28]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)
print('Before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)

Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.1682, 0.0426],
        [0.5605, 0.2556]])

After adding:
tensor([[1.1682, 1.0426],
        [1.5605, 1.2556]])
tensor([[1.1682, 1.0426],
        [1.5605, 1.2556]])
tensor([[0.1682, 0.0426],
        [0.5605, 0.2556]])

After multiplying
tensor([[0.0283, 0.0018],
        [0.3142, 0.0653]])
tensor([[0.0283, 0.0018],
        [0.3142, 0.0653]])


In [29]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)
print(c,"\n")
d = torch.matmul(a, b, out=c)
print(c,"\n") 
assert c is d 
assert id(c) == old_id
torch.rand(2, 2, out=c)
print(c,"\n") 
assert id(c) == old_id 

tensor([[0., 0.],
        [0., 0.]]) 

tensor([[0.7616, 1.0467],
        [1.1544, 1.2714]]) 

tensor([[0.2984, 0.6437],
        [0.1279, 0.5592]]) 

